### PR TITLE
#160795098 Integrate Hound Ci with Server side

### PR DESCRIPTION
**Pull request by phemonick**
#### What does this PR do?
This pull request integrates HoundCI with server side
#### Description of Task to be completed?
 - integrate HoundCI with repo
#### How should this be manually tested?
N/A
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#160795098

### CODE REVIEW

**Comment by andela-moe** [comment]
Looking at the files changed, I do not see any change to the readme file. DId you add a badge or a badge already existed there?

Please let your PR description of what was done reflect the actual reality.

@phemonick

**Comment by phemonick** [comment]
There is an existing badge there. I will remove that from my PR description

**Comment by andela-moe** [comment]
Considering that all you have done with the PR is add a PR template, I suggest you let the PR reflect that and nothing more. The integration with hound has been done on the HoundCI application and the resources for it to use already exist in the repo.

@phemonick

**Comment by phemonick** [comment]
Hello @andela-moe, thanks for your feedback. With regards to the discussion we have been having, I have come to realise that this pull-request is not needed since there is an existing badge in the repo. I suggest this pull request be closed. Any contrary opinion on this?

**Review by kenware — APPROVED** [review]

**Comment by Chieze-Franklin** [comment]
This feature is already existing.

**Pull request closed without merging**
